// src/pages/praesidium.vue
<template>
  <div>
    <section-component title="Praesidium" bg-color="bg-white" text-color="text-blue-950" align-items="items-start">
      <div class="w-full flex flex-col mt-8 gap-4">
        <div v-for="(pr, i) of praesidium" :key="pr.name" class="flex flex-col md:flex-row bg-yellow-50 shadow-lg" :class="i%2 && 'md:flex-row-reverse'">
          <img :src="pr.img" class="max-h-80 md:max-h-60 md:max-w-60 h-full w-full object-cover" />
          <div class="flex flex-col flex-1 p-4 gap-2">
            <h2 class="font-bold text-lg">{{ pr.name }}</h2>
            <span><i>{{ pr.function }}</i></span>
            <p>{{ pr.description }}</p>
          </div>
        </div>
      </div>
    </section-component>
  </div>
</template>

<script lang="ts" setup>
import SectionComponent from '../components/section/index.vue';
import { praesidiumMembers } from '../data/praesidium';
import { preloadImages } from '../utils/helper';

const praesidium = praesidiumMembers.map(v => ({
  ...v,
  img: `/assets/${v.img}`
}));

await preloadImages(praesidium.map(v => v.img));
</script>

// src/pages/praesidium.tsx
import Section from "../components/section"

export const praesidiumMembers = [
  {
    name: "Jarno ’Cremer’ De Cremer",
    function: 'Senior seniorum',
    img: 'cremer.jpeg',
    description: null,
    club: 'Mercurius Aalst',
    doopjaar: '2021',
  },
  {
    name: "Brent ‘Boxer’ Van Huylenbroeck",
    function: 'Vice-Praeses',
    img: 'brent.jpg',
    description: null,
    club: 'Lorem Ipsum',
    doopjaar: '2018',
  },
  {
    name: "Fleur Schiettecat",
    function: 'Ab-actis',
    img: 'fleur.jpeg',
    description: 'Het leven is geven en nemen. Soms neem ik teveel en dan geef ik over.',
    club: 'Mercurius Aalst',
    doopjaar: '2019',
  },
  {
    name: "Jahnke Coppens",
    function: 'Cantor cantorum',
    img: 'jahnke.jpeg',
    description: 'dikken',
    club: 'Lorem Ipsum',
    doopjaar: '2021',
  },
  {
    name: "Ilke Kestemont",
    function: 'Cultuur',
    img: 'Ilke.jpg',
    description: 'optimist tot in de kist!',
    club: 'Mercurius Aalst',
    doopjaar: '2018',
  },
  {
    name: "Amory Gyssens",
    function: 'Sport',
    img: 'amory.jpeg',
    description: "Ja men kinjer’n",
    club: 'Lorem Ipsum',
    doopjaar: '2022',
  },
  {
    name: 'Mitchell ‘Stitch’ Goossens',
    function: 'Quaestor',
    img: 'mitch.jpg',
    description: null,
    club: 'Lorem Ipsum',
    doopjaar: '2016',
  },
]

const Praesidium = () => (
  <Section title="Praesidium" bgColor="bg-white" textColor="text-blue-950" alignItems="items-start">
    <div className="w-full flex flex-col !mt-8 gap-4">
      {praesidiumMembers.map(pr => (
        <div key={pr.name} className="flex flex-col md:flex-row even:md:flex-row-reverse bg-yellow-50 shadow-lg">
          <img src={`/assets/images/praesidium/${pr.img}`} className="max-h-80 md:max-h-60 md:max-w-60 h-full w-full object-cover" />
          <div className="flex flex-col flex-1 !p-4 !gap-2">
            <h2 className="font-bold text-lg">{pr.name}</h2>
            <span><i>{pr.function}</i></span>
            <p>{pr.description}</p>
            <p>{pr.club} - {pr.doopjaar}</p>
        </div>
      </div>
      ))}
    </div>
  </Section>
)

export default Praesidium
